[package]
name = "jira-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = {version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
ellipse = "0.2.0"
itertools = "0.14.0"
clearscreen = "4.0.0"

[dev-dependencies]
tempfile = "3.3.0"